use anchor_lang::prelude::*;

// Use the program id you deployed earlier (keep as-is)
declare_id!("AiBawWM1dhGBfgs8dR8QidWhvFEu6MhfrtohbwCqeb8u");

#[program]
pub mod anchor_crud_item {
    use super::*;

    /// Create a new Item account (PDA: [b"item", owner, id_le_bytes])
    pub fn create(ctx: Context<CreateItem>, id: u64, name: String, value: u32) -> Result<()> {
        // basic validation (bytes)
        if name.as_bytes().len() > Item::NAME_MAX_LEN {
            return Err(ErrorCode::NameTooLong.into());
        }

        let item = &mut ctx.accounts.item;
        item.owner = ctx.accounts.user.key();
        item.id = id;
        item.write_name(&name);
        item.value = value;
        // bump generated by the `init` attribute is available on `ctx.bumps.item`
        item.bump = ctx.bumps.item;
        Ok(())
    }

    /// Update name and value of an existing Item (only owner)
    pub fn update(ctx: Context<UpdateItem>, _id: u64, name: String, value: u32) -> Result<()> {
        if name.as_bytes().len() > Item::NAME_MAX_LEN {
            return Err(ErrorCode::NameTooLong.into());
        }

        let item = &mut ctx.accounts.item;
        // ownership is enforced by `has_one = owner` in the Accounts struct
        item.write_name(&name);
        item.value = value;
        Ok(())
    }

    /// Delete (close) the Item account and return lamports to the owner
    pub fn delete(_ctx: Context<DeleteItem>, _id: u64) -> Result<()> {
        // `close = owner` in the account attribute will transfer lamports back to owner
        Ok(())
    }

    /// Read: emits an event containing the account data for convenience.
    pub fn read(ctx: Context<ReadItem>, _id: u64) -> Result<()> {
        let item = &ctx.accounts.item;
        emit!(ItemEvent {
            owner: item.owner,
            id: item.id,
            name: item.read_name(),
            value: item.value,
        });
        Ok(())
    }
}

/// Account storing the simple struct (name stored as fixed-length byte array)
#[account]
pub struct Item {
    pub owner: Pubkey,       // who created / controls this item
    pub id: u64,
    pub name: [u8; Item::NAME_MAX_LEN], // fixed-size name buffer
    pub value: u32,
    pub bump: u8,
}

impl Item {
    // sizing constants
    pub const NAME_MAX_LEN: usize = 50; // maximum bytes for name
    // discriminator (8) + owner (32) + id (8) + name (NAME_MAX_LEN) + value (4) + bump (1)
    pub const LEN: usize = 8 + 32 + 8 + Self::NAME_MAX_LEN + 4 + 1;

    /// helper: write a &str into name buffer (UTF-8 truncated)
    pub fn write_name(&mut self, s: &str) {
        let bytes = s.as_bytes();
        let mut buf = [0u8; Self::NAME_MAX_LEN];
        let copy_len = bytes.len().min(Self::NAME_MAX_LEN);
        buf[..copy_len].copy_from_slice(&bytes[..copy_len]);
        self.name = buf;
    }

    /// helper: read name as String (stop at first 0)
    pub fn read_name(&self) -> String {
        let end = self.name.iter().position(|&b| b == 0).unwrap_or(Self::NAME_MAX_LEN);
        String::from_utf8_lossy(&self.name[..end]).to_string()
    }
}

/// Event emitted by the `read` instruction
#[event]
pub struct ItemEvent {
    pub owner: Pubkey,
    pub id: u64,
    pub name: String,
    pub value: u32,
}

// ----------------- Accounts structs -----------------

#[derive(Accounts)]
#[instruction(id: u64)]
pub struct CreateItem<'info> {
    /// The user who pays for initialization and becomes the owner
    #[account(mut)]
    pub user: Signer<'info>,

    /// The PDA account to store the Item. PDA =
    /// seeds: [b"item", user.key(), id.to_le_bytes()]
    #[account(
        init,
        payer = user,
        space = Item::LEN,
        seeds = [b"item", user.key().as_ref(), &id.to_le_bytes()],
        bump
    )]
    pub item: Account<'info, Item>,

    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
#[instruction(id: u64)]
pub struct UpdateItem<'info> {
    /// The owner (must sign)
    pub owner: Signer<'info>,

    /// account must be mutable; enforce PDA derivation and owner equality
    #[account(
        mut,
        seeds = [b"item", owner.key().as_ref(), &id.to_le_bytes()],
        bump = item.bump,
        has_one = owner
    )]
    pub item: Account<'info, Item>,
}

#[derive(Accounts)]
#[instruction(id: u64)]
pub struct DeleteItem<'info> {
    /// The owner (must sign and will receive the rent-exempt lamports from close)
    pub owner: Signer<'info>,

    /// closing the account returns lamports to `owner`
    #[account(
        mut,
        close = owner,
        seeds = [b"item", owner.key().as_ref(), &id.to_le_bytes()],
        bump = item.bump,
        has_one = owner
    )]
    pub item: Account<'info, Item>,
}

#[derive(Accounts)]
#[instruction(id: u64)]
pub struct ReadItem<'info> {
    /// The owner's public key is used to derive the PDA; this account does not need to sign
    /// so we accept an UncheckedAccount<'info> to allow read by anyone who knows owner+id.
    ///
    /// CHECK: This account is only used for its `pubkey()` when deriving the PDA. No
    /// runtime checks are required because the PDA check on `item` verifies correctness.
    pub owner: UncheckedAccount<'info>,

    /// The item account (readonly)
    #[account(
        seeds = [b"item", owner.key().as_ref(), &id.to_le_bytes()],
        bump = item.bump
    )]
    pub item: Account<'info, Item>,
}

// ----------------- Errors -----------------

#[error_code]
pub enum ErrorCode {
    #[msg("Name exceeds maximum length (50 bytes)")]
    NameTooLong = 6000,

    #[msg("Unauthorized")]
    Unauthorized,

    #[msg("Invalid input")]
    InvalidInput,
}